spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxiStop
    username: root
    password: lalorsh6471!


  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true


server:
  port: 8443
  ssl:
    enabled: true
    protocol: TLS
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: tomcat









