spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxiStop
    username: root
    password: lalorsh6471!


  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true

